### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by YilinGao-SHU** [Duankaiwen/PyCenterNet#7]
Hello, when I install mmdet and run setup.py I find that the readme.md file is missing

code: python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 133, in <module>
    long_description=readme(),
  File "setup.py", line 11, in readme
    with open('README.md', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by Duankaiwen** [comment]
@YilinGao-SHU Move  README.md to code/

**Comment by YilinGao-SHU** [comment]
> @YilinGao-SHU Move README.md to code/
Thanks, I got it
