### ISSUE TITLE
mmcv error

### ISSUE THREAD

**Issue by YilinGao-SHU** [Duankaiwen/PyCenterNet#9]
Hello, something happened when I'm installing mmcv, with
cuda == 11.3
pytorch == 1.11

Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full

    adding license file 'LICENSES.md'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._ext' extension
    Emitting ninja build file /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Using envvar MAX_JOBS (4) as the number of workers...
    /nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    /nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/utils/cpp_extension.py:788: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
      warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
    [1/41] /usr/local/cuda-11.5/bin/nvcc  -DMMCV_WITH_CUDA -I/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/TH -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.5/include -I/nvme1/anaconda3/envs/gyl_mmdetection/include/python3.7m -c -c /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/cc_attention_cuda.cu -o /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/cc_attention_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    FAILED: /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/cc_attention_cuda.o
    /usr/local/cuda-11.5/bin/nvcc  -DMMCV_WITH_CUDA -I/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/TH -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.5/include -I/nvme1/anaconda3/envs/gyl_mmdetection/include/python3.7m -c -c /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/cc_attention_cuda.cu -o /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/cc_attention_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
    /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/cc_attention_cuda.cu:4:10: fatal error: THC/THC.h: No such file or directory
     #include <THC/THC.h>
              ^~~~~~~~~~~
    compilation terminated.
    [2/41] c++ -MMD -MF /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/deform_conv.o.d -pthread -B /nvme1/anaconda3/envs/gyl_mmdetection/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/TH -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.5/include -I/nvme1/anaconda3/envs/gyl_mmdetection/include/python3.7m -c -c /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/deform_conv.cpp -o /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/deform_conv.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    [3/41] c++ -MMD -MF /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/contour_expand.o.d -pthread -B /nvme1/anaconda3/envs/gyl_mmdetection/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/TH -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.5/include -I/nvme1/anaconda3/envs/gyl_mmdetection/include/python3.7m -c -c /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/contour_expand.cpp -o /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/contour_expand.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/contour_expand.cpp: In function ‘std::vector<std::vector<int, std::allocator<int> > > contour_expand(at::Tensor, at::Tensor, int, int)’:
    /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/contour_expand.cpp:104:15: warning: variable ‘label_map_shape’ set but not used [-Wunused-but-set-variable]
       IntArrayRef label_map_shape = internal_kernel_label.sizes();
                   ^~~~~~~~~~~~~~~
    [4/41] c++ -MMD -MF /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/corner_pool.o.d -pthread -B /nvme1/anaconda3/envs/gyl_mmdetection/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/TH -I/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.5/include -I/nvme1/anaconda3/envs/gyl_mmdetection/include/python3.7m -c -c /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/mmcv/ops/csrc/pytorch/corner_pool.cpp -o /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch/corner_pool.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
        env=env)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/setup.py", line 343, in <module>
        zip_safe=False)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/command/develop.p
        build_ext.build_extensions(self)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/nvme1/anaconda3/envs/gyl_mmdetection/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /nvme1/anaconda3/envs/gyl_mmdetection/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/setup.py'"'"'; __file__='"'"'/server8/gyl/Data_clean/PyCenterNet-master/code/mmcv/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by Duankaiwen** [comment]
@YilinGao-SHU  Try pytorch == 1.5.0

**Comment by YilinGao-SHU** [comment]
> @YilinGao-SHU Try pytorch == 1.5.0

Thank you very much for your advice, after following your suggestions I managed to configure the environment, but when I started training I got the following error

Traceback (most recent call last):
  File "tools/train_ccpd.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/datasets/__init__.py", line 10, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/models/dense_heads/__init__.py", line 31, in <module>
    from .pycenternet_head import PyCenterNetHead
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/models/dense_heads/pycenternet_head.py", line 11, in <module>
    from mmdet.ops import TLPool, BRPool
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/ops/__init__.py", line 1, in <module>
    from .corner_pool import CornerPool, TLPool, BRPool
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/ops/corner_pool/__init__.py", line 1, in <module>
    from .corner_pool import CornerPool, TLPool, BRPool
  File "/server8/gyl/Data_clean/PyCenterNet-master/code/mmdet/ops/corner_pool/corner_pool.py", line 7, in <module>
    from . import corner_pool_ext
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

And this is my environment：
mmcv-full           1.3.9       /server8/gyl/Data_clean/PyCenterNet-master/code/mmcv
mmdet               2.11.0      /server8/gyl/Data_clean/PyCenterNet-master/code
mmpycocotools       12.0.3      /server8/gyl/Data_clean/PyCenterNet-master/code/mmpycocotools
torch               1.5.0+cu101
torchvision         0.6.0+cu101
>>> print(torch.cuda.is_available())
True
>>> print(torch.version.cuda)
10.1
>>> print(torch.backends.cudnn.version())
7603

**Comment by Duankaiwen** [comment]
@YilinGao-SHU 
Please refer to this [issue](https://github.com/open-mmlab/mmdetection/issues/2627)

**Comment by YilinGao-SHU** [comment]
> @YilinGao-SHU Please refer to this [issue](https://github.com/open-mmlab/mmdetection/issues/2627)

Thank you for your suggestion, a re-build will fix this bug 👍
